package com.example.projekatidemovozom;

public class AdditionalCities {
    public static String[] additionalCities = {
            "Golubinci",
            "Putinci",
            "Kraljevci",
            "Voganj",
            "Martinci",
            "Kukujevci-Erdevik",
            "Nova Pazova",
            "Batajnica",
            "Karađorđev Park",
            "Vukov spomenik",
            "Pančevački most",
            "Pančevo glavna",
            "Pančevo varoš",
            "Banatsko Novo Selo",
            "Vladimirovac",
            "Banatski Karlovac",
            "Nikolinci",
            "Uljma",
            "Vlajkovac",
            "Rakovica",
            "Resnik",
            "Ripanj",
            "Ralja",
            "Sopot Kosmajski",
            "Mladenovac",
            "Kovačevac",
            "Rabrovac",
            "Kusadak",
            "Ratare",
            "Glibovac",
            "Palanka",
            "Mala Plana",
            "Velika Plana",
            "Staro Selo",
            "Novo Selo",
            "Markovac",
            "Lapovo Varoš",
            "Lapovo Ražirna stanica",
            "Lapovo",
            "Brzan",
            "Miloševo",
            "Bagrdan",
            "Lanište",
            "Bukovce",
            "Gilje",
            "Sikirica-Ratari",
            "Drenovac",
            "Ćićevac",
            "Lučina",
            "Stalać",
            "Braljina",
            "Cerovac ražanj",
            "Staro Trubarevo",
            "Đunis",
            "Vitkovac stajalište",
            "Donji Ljubeš",
            "Gornji Ljubeš",
            "Korman",
            "Trnjani",
            "Adrovac",
            "Nozrina",
            "Lužane",
            "Tešica",
            "Grejač",
            "Supovački most",
            "Mezgraja",
            "Vrtište",
            "Trupale",
            "Crveni Krst"
    };
}